[package]
name = "dprint-development"
description = "Helper functions for testing dprint plugins."
version = "0.2.2"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
console = "0.14.0"
similar = "0.5.0"
